# loop through microservices

{{- range $name, $config := .Values.microservices }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.appName }}-deployment
  labels:
    app.kubernetes.io/name: {{ $config.appName }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ $config.replicaCount | default $.Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.appName }}
  template:
    metadata:
      labels:
        app: {{ $config.appName }}
    spec:
      containers:
      - name: {{ $config.appName }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        ports:
          - containerPort: {{ $config.containerPort }}
        env:
        {{- range $config.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}