---
name: CI Pipeline new
# Builds Docker images for each microservice & pushes them to Docker Hub
on:
  push:
    branches:
      - helm
    tags:
      - '*'
  workflow_dispatch: # allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest 
    env:
      IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }} # use environment variables to pick between push events and tag push  events
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ env.IMAGE_TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest ./multi-stack-application/vote
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:${{ env.IMAGE_TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest ./multi-stack-application/result
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ env.IMAGE_TAG }} -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./multi-stack-application/worker
      
      - name: Push Docker images
        run: |        
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

      